name: 'build-test'
on:
  pull_request:
  push:
    branches-ignore:
      - master
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn package
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/

  test:
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Install with no params
        uses: ./
        id: setup-chrome
      - if: runner.os == 'Linux'
        run:
          # Linux or windows
          # chrome --version
          # macOS
          # chromium --version
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
